[project]
name = "python-tooling-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.15.0",
    "ty>=0.0.15",
]
